version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: docker-publishing
          filters:
            branches:
              only: [ main ]

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: Build and Release
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker build -t docker.io/skpr/aws-efs-csi-driver:v1.4.2 .
            docker push docker.io/skpr/aws-efs-csi-driver:v1.4.2
